//MADE USING CHAGTGPT
export const countryList = [
  { country: "United Arab Emirates", code2: "AE", code3: "AED" },
  { country: "Afghanistan", code2: "AF", code3: "AFN" },
  { country: "Antigua and Barbuda", code2: "AG", code3: "XCD" },
  { country: "Albania", code2: "AL", code3: "ALL" },
  { country: "Armenia", code2: "AM", code3: "AMD" },
  { country: "Netherlands Antilles", code2: "AN", code3: "ANG" },
  { country: "Angola", code2: "AO", code3: "AOA" },
  { country: "Antarctica", code2: "AQ", code3: "AQD" },
  { country: "Argentina", code2: "AR", code3: "ARS" },
  { country: "Australia", code2: "AU", code3: "AUD" },
  { country: "Azerbaijan", code2: "AZ", code3: "AZN" },
  { country: "Bosnia and Herzegovina", code2: "BA", code3: "BAM" },
  { country: "Barbados", code2: "BB", code3: "BBD" },
  { country: "Bangladesh", code2: "BD", code3: "BDT" },
  { country: "Belgium", code2: "BE", code3: "XOF" },
  { country: "Bulgaria", code2: "BG", code3: "BGN" },
  { country: "Bahrain", code2: "BH", code3: "BHD" },
  { country: "Burundi", code2: "BI", code3: "BIF" },
  { country: "Bermuda", code2: "BM", code3: "BMD" },
  { country: "Brunei", code2: "BN", code3: "BND" },
  { country: "Bolivia", code2: "BO", code3: "BOB" },
  { country: "Brazil", code2: "BR", code3: "BRL" },
  { country: "Bahamas", code2: "BS", code3: "BSD" },
  { country: "Botswana", code2: "BW", code3: "BWP" },
  { country: "Belarus", code2: "BY", code3: "BYR" },
  { country: "Belize", code2: "BZ", code3: "BZD" },
  { country: "Canada", code2: "CA", code3: "CAD" },
  { country: "Congo (DRC)", code2: "CD", code3: "CDF" },
  { country: "Central African Republic", code2: "CF", code3: "XAF" },
  { country: "Switzerland", code2: "CH", code3: "CHF" },
  { country: "Chile", code2: "CL", code3: "CLP" },
  { country: "China", code2: "CN", code3: "CNY" },
  { country: "Colombia", code2: "CO", code3: "COP" },
  { country: "Costa Rica", code2: "CR", code3: "CRC" },
  { country: "Cuba", code2: "CU", code3: "CUP" },
  { country: "Cape Verde", code2: "CV", code3: "CVE" },
  { country: "Cyprus", code2: "CY", code3: "CYP" },
  { country: "Czech Republic", code2: "CZ", code3: "CZK" },
  { country: "Djibouti", code2: "DJ", code3: "DJF" },
  { country: "Denmark", code2: "DK", code3: "DKK" },
  { country: "Dominican Republic", code2: "DO", code3: "DOP" },
  { country: "Algeria", code2: "DZ", code3: "DZD" },
  { country: "Ecuador", code2: "EC", code3: "ECS" },
  { country: "Estonia", code2: "EE", code3: "EEK" },
  { country: "Egypt", code2: "EG", code3: "EGP" },
  { country: "Ethiopia", code2: "ET", code3: "ETB" },
  { country: "France", code2: "FR", code3: "EUR" },
  { country: "Fiji", code2: "FJ", code3: "FJD" },
  { country: "Falkland Islands", code2: "FK", code3: "FKP" },
  { country: "United Kingdom", code2: "GB", code3: "GBP" },
  { country: "Georgia", code2: "GE", code3: "GEL" },
  { country: "Guernsey", code2: "GG", code3: "GGP" },
  { country: "Ghana", code2: "GH", code3: "GHS" },
  { country: "Gibraltar", code2: "GI", code3: "GIP" },
  { country: "Gambia", code2: "GM", code3: "GMD" },
  { country: "Guinea", code2: "GN", code3: "GNF" },
  { country: "Guatemala", code2: "GT", code3: "GTQ" },
  { country: "Guyana", code2: "GY", code3: "GYD" },
  { country: "Hong Kong", code2: "HK", code3: "HKD" },
  { country: "Honduras", code2: "HN", code3: "HNL" },
  { country: "Croatia", code2: "HR", code3: "HRK" },
  { country: "Haiti", code2: "HT", code3: "HTG" },
  { country: "Hungary", code2: "HU", code3: "HUF" },
  { country: "Indonesia", code2: "ID", code3: "IDR" },
  { country: "Israel", code2: "IL", code3: "ILS" },
  { country: "India", code2: "IN", code3: "INR" },
  { country: "Iraq", code2: "IQ", code3: "IQD" },
  { country: "Iran", code2: "IR", code3: "IRR" },
  { country: "Iceland", code2: "IS", code3: "ISK" },
  { country: "Jamaica", code2: "JM", code3: "JMD" },
  { country: "Jordan", code2: "JO", code3: "JOD" },
  { country: "Japan", code2: "JP", code3: "JPY" },
  { country: "Kenya", code2: "KE", code3: "KES" },
  { country: "Kyrgyzstan", code2: "KG", code3: "KGS" },
  { country: "Cambodia", code2: "KH", code3: "KHR" },
  { country: "Comoros", code2: "KM", code3: "KMF" },
  { country: "North Korea", code2: "KP", code3: "KPW" },
  { country: "South Korea", code2: "KR", code3: "KRW" },
  { country: "Kuwait", code2: "KW", code3: "KWD" },
  { country: "Cayman Islands", code2: "KY", code3: "KYD" },
  { country: "Kazakhstan", code2: "KZ", code3: "KZT" },
  { country: "Laos", code2: "LA", code3: "LAK" },
  { country: "Lebanon", code2: "LB", code3: "LBP" },
  { country: "Sri Lanka", code2: "LK", code3: "LKR" },
  { country: "Liberia", code2: "LR", code3: "LRD" },
  { country: "Lesotho", code2: "LS", code3: "LSL" },
  { country: "Lithuania", code2: "LT", code3: "LTL" },
  { country: "Latvia", code2: "LV", code3: "LVL" },
  { country: "Libya", code2: "LY", code3: "LYD" },
  { country: "Morocco", code2: "MA", code3: "MAD" },
  { country: "Moldova", code2: "MD", code3: "MDL" },
  { country: "Madagascar", code2: "MG", code3: "MGA" },
  { country: "North Macedonia", code2: "MK", code3: "MKD" },
  { country: "Myanmar", code2: "MM", code3: "MMK" },
  { country: "Mongolia", code2: "MN", code3: "MNT" },
  { country: "Macau", code2: "MO", code3: "MOP" },
  { country: "Mauritania", code2: "MR", code3: "MRO" },
  { country: "Malta", code2: "MT", code3: "MTL" },
  { country: "Mauritius", code2: "MU", code3: "MUR" },
  { country: "Maldives", code2: "MV", code3: "MVR" },
  { country: "Malawi", code2: "MW", code3: "MWK" },
  { country: "Mexico", code2: "MX", code3: "MXN" },
  { country: "Malaysia", code2: "MY", code3: "MYR" },
  { country: "Mozambique", code2: "MZ", code3: "MZN" },
  { country: "Namibia", code2: "NA", code3: "NAD" },
  { country: "New Caledonia", code2: "NC", code3: "XPF" },
  { country: "Nigeria", code2: "NG", code3: "NGN" },
  { country: "Nicaragua", code2: "NI", code3: "NIO" },
  { country: "Nepal", code2: "NP", code3: "NPR" },
  { country: "New Zealand", code2: "NZ", code3: "NZD" },
  { country: "Oman", code2: "OM", code3: "OMR" },
  { country: "Panama", code2: "PA", code3: "PAB" },
  { country: "Peru", code2: "PE", code3: "PEN" },
  { country: "Papua New Guinea", code2: "PG", code3: "PGK" },
  { country: "Philippines", code2: "PH", code3: "PHP" },
  { country: "Pakistan", code2: "PK", code3: "PKR" },
  { country: "Poland", code2: "PL", code3: "PLN" },
  { country: "Paraguay", code2: "PY", code3: "PYG" },
  { country: "Qatar", code2: "QA", code3: "QAR" },
  { country: "Romania", code2: "RO", code3: "RON" },
  { country: "Serbia", code2: "RS", code3: "RSD" },
  { country: "Russia", code2: "RU", code3: "RUB" },
  { country: "Rwanda", code2: "RW", code3: "RWF" },
  { country: "Saudi Arabia", code2: "SA", code3: "SAR" },
  { country: "Solomon Islands", code2: "SB", code3: "SBD" },
  { country: "Seychelles", code2: "SC", code3: "SCR" },
  { country: "Sudan", code2: "SD", code3: "SDG" },
  { country: "Sweden", code2: "SE", code3: "SEK" },
  { country: "Singapore", code2: "SG", code3: "SGD" },
  { country: "Slovakia", code2: "SK", code3: "SKK" },
  { country: "Sierra Leone", code2: "SL", code3: "SLL" },
  { country: "Somalia", code2: "SO", code3: "SOS" },
  { country: "Suriname", code2: "SR", code3: "SRD" },
  { country: "Sao Tome and Principe", code2: "ST", code3: "STD" },
  { country: "El Salvador", code2: "SV", code3: "SVC" },
  { country: "Syria", code2: "SY", code3: "SYP" },
  { country: "Eswatini", code2: "SZ", code3: "SZL" },
  { country: "Thailand", code2: "TH", code3: "THB" },
  { country: "Tajikistan", code2: "TJ", code3: "TJS" },
  { country: "Turkmenistan", code2: "TM", code3: "TMT" },
  { country: "Tunisia", code2: "TN", code3: "TND" },
  { country: "Tonga", code2: "TO", code3: "TOP" },
  { country: "Turkey", code2: "TR", code3: "TRY" },
  { country: "Trinidad and Tobago", code2: "TT", code3: "TTD" },
  { country: "Taiwan", code2: "TW", code3: "TWD" },
  { country: "Tanzania", code2: "TZ", code3: "TZS" },
  { country: "Ukraine", code2: "UA", code3: "UAH" },
  { country: "Uganda", code2: "UG", code3: "UGX" },
  { country: "United States", code2: "US", code3: "USD" },
  { country: "Uruguay", code2: "UY", code3: "UYU" },
  { country: "Uzbekistan", code2: "UZ", code3: "UZS" },
  { country: "Venezuela", code2: "VE", code3: "VEF" },
  { country: "Vietnam", code2: "VN", code3: "VND" },
  { country: "Vanuatu", code2: "VU", code3: "VUV" },
  { country: "Yemen", code2: "YE", code3: "YER" },
  { country: "South Africa", code2: "ZA", code3: "ZAR" },
  { country: "Zambia", code2: "ZM", code3: "ZMK" },
  { country: "Zimbabwe", code2: "ZW", code3: "ZWD" }
];
